/*
ALTER SESSION SET "_oracle_script" = TRUE;
CREATE USER residuos IDENTIFIED BY residuos;
GRANT CONNECT , RESOURCE , DBA TO residuos;
*/

--Ejercicio 1: 

SELECT e.NOMBRE_EMPRESA 
FROM EMPRESAPRODUCTORA e 
WHERE e.CIUDAD_EMPRESA LIKE 'Huelva' OR e.CIUDAD_EMPRESA LIKE 'Malaga'
ORDER BY e.NOMBRE_EMPRESA DESC;

--Ejercicio 2:

SELECT d.NOMBRE_DESTINO 
FROM DESTINO d 
WHERE UPPER(d.CIUDAD_DESTINO) LIKE '%B%';

--Ejercicio 3:

SELECT rc.COD_RESIDUO 
FROM RESIDUO_CONSTITUYENTE rc 
WHERE rc.CANTIDAD>4 AND rc.COD_CONSTITUYENTE=113;

--Ejercicio 4:

SELECT t.TIPO_TRANSPORTE,t.KMS,t.COSTE 
FROM TRASLADO t 
WHERE t.FECHA_ENVIO 
BETWEEN TO_DATE('01/12/1994', 'DD/MM/YYYY') AND TO_DATE('31/12/1994', 'DD/MM/YYYY');

-- Ejercicio 5:

SELECT  rc.COD_RESIDUO , COUNT(rc.COD_CONSTITUYENTE) 
FROM  RESIDUO_CONSTITUYENTE rc 
GROUP BY rc.COD_RESIDUO;

-- Ejercicio 6:

SELECT nvl(avg(re.COD_RESIDUO),0)
FROM RESIDUO_EMPRESA re 
WHERE EXTRACT (YEAR FROM fecha)=1994;

-- Ejercicio 7:

SELECT max(t.KMS) 
FROM TRASLADO t 
WHERE EXTRACT(MONTH FROM t.FECHA_ENVIO)=03;

-- Ejercicio 8:

SELECT DISTINCT COUNT(rc.COD_CONSTITUYENTE),t.NIF_EMPRESA  
FROM RESIDUO_CONSTITUYENTE rc ,RESIDUO r ,TRASLADO t 
WHERE rc.COD_RESIDUO =r.COD_RESIDUO 
AND r.COD_RESIDUO=t.COD_RESIDUO 
GROUP BY t.NIF_EMPRESA 
HAVING COUNT(rc.COD_CONSTITUYENTE)>4;

-- Ejercicio 9:

SELECT DISTINCT e.NOMBRE_EMPRESA 
FROM TRASLADO t ,RESIDUO r, EMPRESAPRODUCTORA e 
WHERE t.COD_RESIDUO = r.COD_RESIDUO
AND e.NIF_EMPRESA=t.NIF_EMPRESA 
AND lower (r.OD_RESIDUO) LIKE '%metales%';

-- Ejercicio 10:

SELECT count(t.FECHA_ENVIO),d.CIUDAD_DESTINO,e.CIUDAD_EMPTRANSPORTE 
FROM TRASLADO t,EMPRESATRANSPORTISTA e,DESTINO d
WHERE e.NIF_EMPTRANSPORTE=t.NIF_EMPTRANSPORTE 
AND t.COD_DESTINO =d.COD_DESTINO
GROUP BY d.CIUDAD_DESTINO,e.CIUDAD_EMPTRANSPORTE ; 

-- Ejercicio 11:

-- Ejericicio 12:

SELECT SUM(t.KMS)*
FROM TRASLADO t,em













