/*
ALTER SESSION SET "_oracle_script"=TRUE;
CREATE USER ej2universidad identified BY ej2universidad;
GRANT CONNECT , RESOURCE, DBA TO ej2universidad;
*/

-- Ejercicio 1:

SELECT a.IDTITULACION ,a.NOMBRE,a.COSTEBASICO FROM ASIGNATURA a, TITULACION t 
WHERE a.IDTITULACION =t.IDTITULACION 
ORDER BY  a.COSTEBASICO DESC, a.NOMBRE ASC ; 

--Ejercicio 2:

SELECT p2.NOMBRE ,p2.APELLIDO  FROM PROFESOR p ,PERSONA p2 WHERE p.DNI=p2.DNI ;

--Ejercicio 3:

SELECT a.NOMBRE  FROM ASIGNATURA a,PROFESOR p ,PERSONA p2 
WHERE p2.DNI =p.DNI AND p.IDPROFESOR = a.IDPROFESOR AND p2.CIUDAD ='Sevilla';                        

--Ejercicio 4:

SELECT p.NOMBRE ,p.APELLIDO  FROM ALUMNO a,PERSONA p WHERE a.DNI  = p.DNI; 

--Ejercicio 5:

SELECT p.DNI ,p.NOMBRE ,p.APELLIDO  FROM PERSONA p, ALUMNO a2 WHERE a2.DNI  = p.DNI AND p.CIUDAD ='Sevilla'; 

--Ejercicio 6:


SELECT p.DNI ,p.NOMBRE ,p.APELLIDO  FROM PERSONA p,ALUMNO a,ALUMNO_ASIGNATURA aa,ASIGNATURA a2  
WHERE a.DNI  = p.DNI AND aa.IDALUMNO=a.IDALUMNO AND aa.IDASIGNATURA = a2.IDASIGNATURA AND a2.NOMBRE ='Seguridad Vial';                                          

--Ejercicio 7:

SELECT DISTINCT t.IDTITULACION  FROM TITULACION t, ASIGNATURA a , ALUMNO a2, ALUMNO_ASIGNATURA aa  
WHERE a2.IDALUMNO=aa.IDALUMNO AND aa.IDASIGNATURA =a.IDASIGNATURA AND t.IDTITULACION =a.IDTITULACION AND a2.DNI ='20202020A';

--Ejercicio 8:

SELECT a.NOMBRE FROM ASIGNATURA a, ALUMNO a2, ALUMNO_ASIGNATURA aa, PERSONA p 
WHERE  p.DNI =a2.DNI AND a2.IDALUMNO=aa.IDALUMNO AND aa.IDASIGNATURA =a.IDASIGNATURA AND p.NOMBRE='Rosa' AND p.APELLIDO='Garcia'; 

--Ejercicio 9:

SELECT a.DNI FROM ALUMNO a , PERSONA p ,ALUMNO_ASIGNATURA aa , ASIGNATURA a2,PROFESOR p2
WHERE p.DNI =p2.DNI AND a2.IDPROFESOR =p2.IDPROFESOR AND a.IDALUMNO =aa.IDALUMNO AND aa.IDASIGNATURA =a2.IDASIGNATURA AND p.NOMBRE='Jorge'AND p.APELLIDO= 'Saenz';

--Ejercicio 10:

SELECT a.DNI ,p3.NOMBRE ,p3.apellido FROM ALUMNO a , PERSONA p ,ALUMNO_ASIGNATURA aa , ASIGNATURA a2,PROFESOR p2, PERSONA p3 
WHERE a.IDALUMNO =p3.DNI AND p.DNI =p2.DNI AND a2.IDPROFESOR =p2.IDPROFESOR AND a.IDALUMNO =aa.IDALUMNO AND aa.IDASIGNATURA =a2.IDASIGNATURA AND p.NOMBRE='Jorge'AND p.APELLIDO= 'Saenz';

--Ejercicio 11:

SELECT DISTINCT t.NOMBRE FROM TITULACION t, ASIGNATURA a WHERE t.IDTITULACION =a.IDTITULACION AND a.CREDITOS >=4;


--Ejercicio 12:

SELECT  a.NOMBRE,a.CREDITOS,t.NOMBRE FROM ASIGNATURA a,TITULACION t WHERE t.IDTITULACION(+) =a.IDTITULACION AND a.CUATRIMESTRE =1;

--Ejercicio 13:

SELECT a.NOMBRE , a.COSTEBASICO, p.NOMBRE  FROM ASIGNATURA a,PERSONA p, ALUMNO a2 , ALUMNO_ASIGNATURA aa 
WHERE p.DNI =a2.DNI AND a2.IDALUMNO =aa.IDALUMNO AND a.IDASIGNATURA =aa.IDASIGNATURA AND a.CREDITOS >4.5;

--Ejercicio 14:

SELECT p.NOMBRE  FROM PERSONA p, PROFESOR p2, ASIGNATURA a 
WHERE p.DNI =p2.DNI AND p2.IDPROFESOR =a.IDPROFESOR  AND a.COSTEBASICO BETWEEN 25 AND 35;

--Ejercicio 15:

SELECT DISTINCT  p.NOMBRE FROM ALUMNO a , ASIGNATURA a2, ALUMNO_ASIGNATURA aa, PERSONA p 
WHERE p.DNI =a.DNI AND a.IDALUMNO =aa.IDALUMNO 
AND a2.IDASIGNATURA=aa.IDASIGNATURA 
AND (a2.IDASIGNATURA='150212' AND a2.IDASIGNATURA='130113' OR 
(a2.IDASIGNATURA='150212' OR  a2.IDASIGNATURA='130113'));


--Ejercicio 16:

SELECT a.NOMBRE, t.NOMBRE 
FROM ASIGNATURA a, TITULACION t 
WHERE a.IDTITULACION=t.IDTITULACION 
AND  a.CUATRIMESTRE =2 AND a.CREDITOS!=6;

--Ejercicio 17:

SELECT DISTINCT  a.NOMBRE , a.CREDITOS*10 AS horas, a2.DNI  
FROM ASIGNATURA a,PERSONA p, ALUMNO a2 , ALUMNO_ASIGNATURA aa 
WHERE p.DNI =a2.DNI 
AND a2.IDALUMNO =aa.IDALUMNO 
AND a.IDASIGNATURA =aa.IDASIGNATURA;

--Ejercicio 18:

SELECT p.NOMBRE  
FROM PERSONA p,ASIGNATURA a, ALUMNO_ASIGNATURA aa ,ALUMNO a2 
WHERE p.DNI =a2.DNI 
AND a2.IDALUMNO =aa.IDALUMNO 
AND a.IDASIGNATURA =aa.IDASIGNATURA 
AND p.CIUDAD ='Sevilla' 
AND p.VARON=0;

--Ejercicio 19: 

SELECT a.NOMBRE 
FROM ASIGNATURA a
WHERE a.CUATRIMESTRE=1 
AND a.IDPROFESOR LIKE '%101';        

--Ejercicio 20:                          

SELECT p.NOMBRE  
FROM PERSONA p,ALUMNO_ASIGNATURA aa ,ALUMNO a2 
WHERE p.DNI =a2.DNI 
AND a2.IDALUMNO =aa.IDALUMNO  
AND aa.NUMEROMATRICULA>=3; 

