/*
ALTER SESSION SET "_oracle_script"=TRUE;
CREATE USER ej2universidad identified BY ej2universidad;
GRANT CONNECT , RESOURCE, DBA TO ej2universidad;
*/

-- Ejercicio 1:

SELECT a.NOMBRE,a.COSTEBASICO FROM ASIGNATURA a,TITULACION t
WHERE a.IDTITULACION =t.IDTITULACION ORDER BY  a.COSTEBASICO DESC, a.NOMBRE ASC ;    

--Ejercicio 2:

SELECT p2.NOMBRE ,p2.APELLIDO  FROM PROFESOR p ,PERSONA p2 WHERE p.DNI=p2.DNI ;

--Ejercicio 3:

SELECT a.NOMBRE  FROM ASIGNATURA a,PROFESOR p ,PERSONA p2 
WHERE p2.DNI =p.DNI AND p.IDPROFESOR = a.IDPROFESOR AND p2.CIUDAD ='Sevilla';                        

--Ejercicio 4:

SELECT p.NOMBRE ,p.APELLIDO  FROM ALUMNO a,PERSONA p WHERE a.DNI  = p.DNI; 

--Ejercicio 5:

SELECT p.DNI ,p.NOMBRE ,p.APELLIDO  FROM PERSONA p, ALUMNO a2 WHERE a2.DNI  = p.DNI AND p.CIUDAD ='Sevilla'; 

--Ejercicio 6:


SELECT p.DNI ,p.NOMBRE ,p.APELLIDO  FROM PERSONA p,ALUMNO a,ALUMNO_ASIGNATURA aa,ASIGNATURA a2  
WHERE a.DNI  = p.DNI AND aa.IDALUMNO=a.IDALUMNO AND aa.IDASIGNATURA = a2.IDASIGNATURA AND a2.NOMBRE ='Seguridad Vial';                                          

--Ejercicio 7:

SELECT t.IDTITULACION  FROM TITULACION t,ASIGNATURA a ,ALUMNO a2  WHERE  
