/*
ALTER SESSION SET "_oracle_script" = TRUE;
CREATE USER jardineria IDENTIFIED BY jardineria;
GRANT CONNECT , RESOURCE , DBA TO jardineria;
*/

-- Ejercicio 1:
SELECT c.NOMBRE_CLIENTE 
FROM CLIENTE c 
WHERE c.LIMITE_CREDITO = (SELECT MAX(c2.LIMITE_CREDITO) 
						  FROM CLIENTE c2);
						  
-- Ejercicio 2:
SELECT e.NOMBRE||' '|| e.APELLIDO1, e.PUESTO
FROM EMPLEADO e 
WHERE e.CODIGO_EMPLEADO NOT IN (SELECT DISTINCT c.CODIGO_EMPLEADO_REP_VENTAS
								FROM CLIENTE c);

-- Ejercicio 3:
SELECT p.NOMBRE 
FROM PRODUCTO p 
WHERE p.PRECIO_VENTA = (SELECT max(p2.PRECIO_VENTA) 
						FROM PRODUCTO p2);
-- Ejercicio 4:
SELECT lp.*
from (select p.NOMBRE
      from PRODUCTO  p ,DETALLE_PEDIDO dp
      where p.CODIGO_PRODUCTO=dp.CODIGO_PRODUCTO
      group by dp.CODIGO_PRODUCTO,p.NOMBRE
      order by sum(dp.CANTIDAD) desc) lp
    where ROWNUM=1;

-- Ejercicio 5:
SELECT c.NOMBRE_CLIENTE
FROM CLIENTE c 
WHERE c.LIMITE_CREDITO > (SELECT sum(p.TOTAL)
						  FROM PAGO p
						  WHERE c.CODIGO_CLIENTE=p.CODIGO_CLIENTE );
						 

-- Ejercicio 6: --????????
SELECT DISTINCT p.NOMBRE,p.CANTIDAD_EN_STOCK
FROM PRODUCTO p 
WHERE p.CANTIDAD_EN_STOCK = (SELECT max(p2.CANTIDAD_EN_STOCK)
							 FROM PRODUCTO p2)
OR  p.CANTIDAD_EN_STOCK = (SELECT MIN(p2.CANTIDAD_EN_STOCK)
							 FROM PRODUCTO p2);
							
/*							
SELECT DISTINCT p.NOMBRE 
FROM PRODUCTO p ,(SELECT max(p2.CANTIDAD_EN_STOCK)
							 FROM PRODUCTO p2), (SELECT MIN(p2.CANTIDAD_EN_STOCK)
							 FROM PRODUCTO p2);

							
*/
-- Ejercicio 7: 
SELECT e.NOMBRE, e.APELLIDO1 ,e.EMAIL
FROM EMPLEADO e 
WHERE e.CODIGO_JEFE = (SELECT CODIGO_EMPLEADO
					   FROM EMPLEADO
					   WHERE UPPER(NOMBRE) LIKE 'ALBERTO'
					   AND UPPER(APELLIDO1) LIKE 'SORIA');




							