
ALTER SESSION SET "_oracle_script" = TRUE;
CREATE USER gestion IDENTIFIED BY gestion;
GRANT CONNECT , RESOURCE , DBA TO gestion;
/*
-- Ejercicio 1:

SELECT  f.CODFAC,f.FECHA,f.DTO*2 
FROM FACTURAS f 
WHERE f.IVA=0;

-- Ejercicio 2: 

SELECT f.CODFAC  
FROM FACTURAS f 
WHERE f.IVA IS NULL;

-- Ejercicio 3:

SELECT  f.CODFAC,f.FECHA 
FROM FACTURAS f
WHERE f.IVA=0 OR IVA IS NULL;

-- Ejercicio 4:

SELECT lf.CODFAC, lf.CODART
FROM LINEAS_FAC lf 
WHERE lf.CANT <5 AND lf.DTO>=25;

-- Ejercicio 5:

SELECT a.DESCRIP,a.STOCK_MIN -a.STOCK
FROM ARTICULOS a 
WHERE a.STOCK <a.STOCK_MIN;

-- Ejericico 6:

SELECT DISTINCT f.IVA 
FROM FACTURAS f ;

-- Ejercicio 7:

SELECT a.CODART,a.DESCRIP,a.STOCK_MIN 
FROM ARTICULOS a 
WHERE a.STOCK IS NULL;

-- Ejercicio 8:

SELECT a.DESCRIP
FROM ARTICULOS a 
WHERE a.STOCK>a.STOCK_MIN*3 
AND a.PRECIO>6;

-- Ejercicio 9:

SELECT DISTINCT lf.CODART 
FROM LINEAS_FAC lf 
WHERE lf.CODFAC 
BETWEEN 8  AND 10;

-- Ejercicio 10:

SELECT c.NOMBRE,c.DIRECCION 
FROM CLIENTES c; 

-- Ejercicio 11:

SELECT DISTINCT c.CODPUE 
FROM CLIENTES c;

-- Ejercicio 12:

SELECT DISTINCT c.CODPUE FROM CLIENTES c 
WHERE c.CODCLI<25; ----------------------------------------

-- Ejercicio 13:

SELECT p.NOMBRE FROM PROVINCIAS p 
WHERE p.NOMBRE LIKE '_o%' OR p.NOMBRE LIKE '_O%';

-- Ejercicio 14:

SELECT f.CODFAC, EXTRACT (YEAR FROM f.FECHA)-1 FROM FACTURAS f 
WHERE f.CODCLI BETWEEN 50 AND 100;        

-- Ejercicio 15:

SELECT c.NOMBRE,c.DIRECCION FROM CLIENTES c 
WHERE c.CODPOSTAL LIKE '12%';


-- Ejercicio 16:

SELECT DISTINCT f.FECHA  FROM FACTURAS f 
WHERE f.CODCLI<50;

-- Ejercicio 17:

SELECT f.CODFAC ,f.FECHA FROM FACTURAS f
WHERE f.FECHA BETWEEN f.FECHA TO_DATE('05/2004','MM/YYYY') 
AND f.FECHA TO_DATE('07/2004','MM/YYYY') ; ------------------------

-- Ejercicio 18:

SELECT f.CODFAC ,f.FECHA FROM FACTURAS f
WHERE f.FECHA BETWEEN f.FECHA TO_DATE('05/2004','MM/YYYY') 
AND f.FECHA TO_DATE('07/2004','MM/YYYY') AND f.CODCLI BETWEEN 100 AND 250; ------------------------

-- Ejercicio 19:

SELECT f.CODFAC, f.FECHA FROM FACTURAS f 
WHERE f.CODCLI BETWEEN 90 AND 100 AND (f.IVA IS NULL OR f.IVA=0);

-- Ejercicio 20:

SELECT p.NOMBRE FROM PROVINCIAS p 
WHERE p.NOMBRE LIKE '%S' OR p.NOMBRE LIKE '%s';

-- Ejercicio 21:

SELECT c.NOMBRE FROM CLIENTES c 
WHERE c.CODPOSTAL LIKE '02%' 
OR  c.CODPOSTAL LIKE '11%' 
OR  c.CODPOSTAL LIKE '21%';

-- Ejercicio 22:

SELECT * FROM ARTICULOS a 
WHERE a.STOCK>a.STOCK_MIN 
AND a.STOCK -a.STOCK_MIN 
BETWEEN 0 AND 5;

-- Ejercicio 23:

SELECT p.NOMBRE FROM PROVINCIAS p 
WHERE p.NOMBRE LIKE '%ma%' OR p.NOMBRE LIKE '%MA%';
*/






