/*
ALTER SESSION SET "_oracle_script" = TRUE;
CREATE USER residuos IDENTIFIED BY residuos;
GRANT CONNECT , RESOURCE , DBA TO residuos;
*/

--Ejercicio 1: 

SELECT e.NOMBRE_EMPRESA 
FROM EMPRESAPRODUCTORA e 
WHERE e.CIUDAD_EMPRESA LIKE 'Huelva' OR e.CIUDAD_EMPRESA LIKE 'Malaga'
ORDER BY e.NOMBRE_EMPRESA DESC;

--Ejercicio 2:

SELECT d.NOMBRE_DESTINO 
FROM DESTINO d 
WHERE UPPER(d.CIUDAD_DESTINO) LIKE '%B%';

--Ejercicio 3:

SELECT rc.COD_RESIDUO 
FROM RESIDUO_CONSTITUYENTE rc 
WHERE rc.CANTIDAD>4 AND rc.COD_CONSTITUYENTE=113;

--Ejercicio 4:

SELECT t.TIPO_TRANSPORTE,t.KMS,t.COSTE 
FROM TRASLADO t 
WHERE t.FECHA_ENVIO 
BETWEEN TO_DATE('01/12/1994', 'DD/MM/YYYY') AND TO_DATE('31/12/1994', 'DD/MM/YYYY');

-- Ejercicio 5:

SELECT 






