-- CONSULTAS MULTITABLA (COMPOSICION INTERNA);
-- Ejercicio 1:
SELECT c.NOMBRE_CLIENTE,e.NOMBRE,e.APELLIDO1 
FROM CLIENTE c,EMPLEADO e 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS =e.CODIGO_EMPLEADO;

-- Ejercicio 2:

SELECT c.NOMBRE_CLIENTE,e.NOMBRE
FROM CLIENTE c,EMPLEADO e,PAGO p 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS =e.CODIGO_EMPLEADO
AND c.CODIGO_CLIENTE =p.CODIGO_CLIENTE;

-- Ejercicio 3:

SELECT DISTINCT c.NOMBRE_CLIENTE,e.NOMBRE
FROM CLIENTE c,EMPLEADO e,PAGO p 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS =e.CODIGO_EMPLEADO
AND c.CODIGO_CLIENTE NOT IN (SELECT p2.CODIGO_CLIENTE 
							FROM PAGO p2);
						
-- Ejercicio 4:
SELECT DISTINCT C.NOMBRE_CLIENTE, E.NOMBRE, O.CIUDAD 
FROM CLIENTE C, PAGO P, EMPLEADO E, OFICINA O
WHERE C.CODIGO_CLIENTE NOT IN 
        (SELECT P.CODIGO_CLIENTE 
         FROM PAGO P)
AND C.CODIGO_EMPLEADO_REP_VENTAS = E.CODIGO_EMPLEADO 
AND E.CODIGO_OFICINA = O.CODIGO_OFICINA;
  
 -- Ejercicio 5:
SELECT O.LINEA_DIRECCION1, O.LINEA_DIRECCION2 
FROM OFICINA O, EMPLEADO E, CLIENTE C
WHERE O.CODIGO_OFICINA = E.CODIGO_OFICINA 
AND E.CODIGO_EMPLEADO = C.CODIGO_EMPLEADO_REP_VENTAS 
AND UPPER(C.CIUDAD) LIKE 'FUENLABRADA';
			
-- Ejercicio 6:
SELECT C.NOMBRE_CLIENTE, E.NOMBRE, O.CODIGO_OFICINA 
FROM CLIENTE C, EMPLEADO E, OFICINA O
WHERE E.CODIGO_EMPLEADO = C.CODIGO_EMPLEADO_REP_VENTAS
AND E.CODIGO_OFICINA = O.CODIGO_OFICINA;

--Ejercicio 8:
 SELECT E.NOMBRE AS EMPLEADO, E2.NOMBRE AS JEFE
FROM EMPLEADO E, EMPLEADO E2
WHERE E.CODIGO_EMPLEADO = E2.CODIGO_JEFE;

-- Ejercicio 9:
SELECT DISTINCT C.NOMBRE_CLIENTE 
FROM CLIENTE C, PEDIDO P
WHERE C.CODIGO_CLIENTE = P.CODIGO_CLIENTE 
AND P.FECHA_ESPERADA < P.FECHA_ENTREGA;

-- Ejercicio 10:

SELECT DISTINCT PR.GAMA, C.NOMBRE_CLIENTE 
FROM CLIENTE C, PEDIDO P, DETALLE_PEDIDO DP, PRODUCTO PR
WHERE C.CODIGO_CLIENTE = P.CODIGO_CLIENTE 
AND P.CODIGO_PEDIDO = DP.CODIGO_PEDIDO 
AND DP.CODIGO_PRODUCTO = PR.CODIGO_PRODUCTO;



-- CONSULTAS MULTITABLA (COMPOSICION EXTERNA);

-- Ejercicio 1:
SELECT DISTINCT C.NOMBRE_CLIENTE 
FROM CLIENTE C 
WHERE C.CODIGO_CLIENTE NOT IN 
        (SELECT P.CODIGO_CLIENTE 
         FROM PAGO P);

-- Ejercicio 2 :
SELECT DISTINCT C.NOMBRE_CLIENTE 
FROM CLIENTE C
WHERE C.CODIGO_CLIENTE NOT IN 
        (SELECT P.CODIGO_CLIENTE 
         FROM PEDIDO P);

-- Ejercicio 3:
SELECT DISTINCT C.NOMBRE_CLIENTE 
FROM CLIENTE C
WHERE C.CODIGO_CLIENTE NOT IN 
        (SELECT P.CODIGO_CLIENTE 
         FROM PEDIDO P)
AND C.CODIGO_CLIENTE NOT IN 
        (SELECT P2.CODIGO_CLIENTE 
         FROM PAGO P2 );

-- Ejercicio 4:
SELECT E.NOMBRE 
FROM EMPLEADO E
WHERE E.CODIGO_OFICINA IS NULL;

-- Ejericicio 5:
SELECT DISTINCT E.NOMBRE 
FROM EMPLEADO E, CLIENTE C
WHERE E.CODIGO_EMPLEADO NOT IN 
        (SELECT C.CODIGO_EMPLEADO_REP_VENTAS 
         FROM CLIENTE C);

-- Ejercicio 6:
SELECT e.NOMBRE
FROM EMPLEADO e 
WHERE e.CODIGO_OFICINA NOT IN (SELECT o.CODIGO_OFICINA 
							   FROM OFICINA o
							   WHERE e.CODIGO_OFICINA=o.CODIGO_OFICINA)
OR  e.CODIGO_EMPLEADO NOT IN (SELECT c.CODIGO_EMPLEADO_REP_VENTAS 
							  FROM CLIENTE c
							  WHERE e.CODIGO_EMPLEADO=c.CODIGO_EMPLEADO_REP_VENTAS);
-- Ejercicio 7:					 
SELECT DISTINCT p.NOMBRE 
FROM PRODUCTO p
WHERE p.CODIGO_PRODUCTO NOT IN (SELECT dp.CODIGO_PRODUCTO 
								FROM DETALLE_PEDIDO dp);
							
-- Ejercicio 8:
SELECT o.CODIGO_OFICINA 
FROM OFICINA o 
WHERE o.CODIGO_OFICINA NOT IN (SELECT e.CODIGO_OFICINA 
								FROM EMPLEADO e,CLIENTE c,DETALLE_PEDIDO dp,PEDIDO p,PRODUCTO p2, GAMA_PRODUCTO gp 
								WHERE e.CODIGO_EMPLEADO=c.CODIGO_EMPLEADO_REP_VENTAS
								AND c.CODIGO_CLIENTE=p.CODIGO_CLIENTE
								AND p.CODIGO_PEDIDO=dp.CODIGO_PEDIDO
								AND dp.CODIGO_PRODUCTO=p2.CODIGO_PRODUCTO
								AND p2.GAMA=gp.GAMA
								AND gp.GAMA LIKE 'Frutales');

-- Ejercicio 9:

SELECT DISTINCT c.NOMBRE_CLIENTE 
FROM CLIENTE c ,PEDIDO p 
WHERE c.CODIGO_CLIENTE=p.CODIGO_CLIENTE 
AND c.CODIGO_CLIENTE NOT IN (SELECT p2.CODIGO_CLIENTE 
							 FROM PAGO p2);

-- Ejercicio 10:
SELECT *
FROM EMPLEADO e
WHERE e.CODIGO_EMPLEADO =e.CODIGO_JEFE
AND e.CODIGO_EMPLEADO NOT IN (SELECT c.CODIGO_EMPLEADO_REP_VENTAS 
							  FROM CLIENTE c);

							 
							 
							 

-- CONSULTAS RESUMEN:
	
							 
							 
					
-- Ejericicio 1:
SELECT count(e.CODIGO_EMPLEADO)
FROM EMPLEADO e;
	
-- Ejercicio2:
 SELECT C.PAIS, COUNT(C.CODIGO_CLIENTE)
    FROM CLIENTE C
    GROUP BY C.PAIS;

-- Ejercicio 3:
SELECT AVG(p.TOTAL)
FROM PAGO p 
WHERE EXTRACT (YEAR FROM p.FECHA_PAGO)=2009;

-- Ejercicio 4:
SELECT P.ESTADO, COUNT(P.CODIGO_PEDIDO) AS NUM_PEDIDOS
FROM PEDIDO P
GROUP BY P.ESTADO 
ORDER BY COUNT(P.CODIGO_PEDIDO) DESC;

-- Ejercicio 5:
SELECT max(p.PRECIO_VENTA),MIN(p.PRECIO_VENTA) 
FROM PRODUCTO p;

-- Ejercicio 6:
SELECT COUNT(C.CODIGO_CLIENTE)
FROM CLIENTE C;
-- Ejercicio 7:
SELECT count(c.CODIGO_CLIENTE)
FROM CLIENTE c 
WHERE LOWER(c.CIUDAD) LIKE 'madrid';
		

-- Ejercicio 8:
SELECT C.CIUDAD, COUNT(C.CODIGO_CLIENTE) AS NUM_CLIENTE
FROM CLIENTE C
WHERE C.CIUDAD LIKE 'M%'
GROUP BY C.CIUDAD;

-- Ejericicio 9:
SELECT e.CODIGO_EMPLEADO,COUNT(c.CODIGO_CLIENTE) 
FROM CLIENTE c,EMPLEADO e 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS=e.CODIGO_EMPLEADO
GROUP BY e.CODIGO_EMPLEADO;

-- Ejercicio 10:
SELECT COUNT(c.CODIGO_CLIENTE) 
FROM CLIENTE c 
WHERE c.CODIGO_EMPLEADO_REP_VENTAS NOT IN (SELECT e.CODIGO_EMPLEADO 
							   FROM EMPLEADO e);

-- Ejercicio 11:
SELECT min(p.FECHA_PAGO), max(p.FECHA_PAGO) 
FROM PAGO p,CLIENTE c 
WHERE p.CODIGO_CLIENTE =c.CODIGO_CLIENTE;

-- Ejercicio 12:

 SELECT DP.CODIGO_PEDIDO, COUNT(DISTINCT DP.CODIGO_PRODUCTO)
 FROM DETALLE_PEDIDO DP
 GROUP BY DP.CODIGO_PEDIDO;

-- Ejercicio 13:
SELECT sum(p.CANTIDAD_EN_STOCK)
FROM PRODUCTO p,PEDIDO p2,DETALLE_PEDIDO dp 
WHERE p.CODIGO_PRODUCTO =dp.CODIGO_PRODUCTO 
AND dp.CODIGO_PEDIDO =p2.CODIGO_PEDIDO;

-- Ejericico 15:
SELECT SUM(DP.CANTIDAD) FACTURACION, DP.PRECIO_UNIDADCANTIDAD BASE_IMPONIBLE, '21%' IVA, SUM(DP.CANTIDAD)+DP.PRECIO_UNIDADCANTIDAD TOTAL_FACTURADO
FROM DETALLE_PEDIDO DP 
GROUP BY DP.PRECIO_UNIDADCANTIDAD;

-- Ejercicio 16:
SELECT SUM(DP.CANTIDAD), DP.PRECIO_UNIDADCANTIDAD, '21%' IVA, SUM(DP.CANTIDAD)+DP.PRECIO_UNIDADCANTIDAD 
FROM DETALLE_PEDIDO DP 
GROUP BY DP.PRECIO_UNIDADCANTIDAD,CODIGO_PRODUCTO;

-- Ejercicio 17:
SELECT SUM(DP.CANTIDAD) , DP.PRECIO_UNIDADCANTIDAD , '21%' IVA, SUM(DP.CANTIDAD)+DP.PRECIO_UNIDADCANTIDAD 
FROM DETALLE_PEDIDO DP 
WHERE CODIGO_PRODUCTO LIKE 'OR%'
GROUP BY DP.PRECIO_UNIDADCANTIDAD,CODIGO_PRODUCTO;

--Ejercicio 18:
SELECT PR.NOMBRE, P.TOTAL,SUM(DP.CANTIDAD)+DP.PRECIO_UNIDADCANTIDAD TOTAL_FACTURADO, (SUM(DP.CANTIDAD)+DP.PRECIO_UNIDADCANTIDAD)21/100 TOTAL_FACTURADO
FROM PAGO P, PRODUCTO PR, DETALLE_PEDIDO DP, PEDIDO P2, CLIENTE C
WHERE P.CODIGO_CLIENTE = C.CODIGO_CLIENTE 
AND C.CODIGO_CLIENTE = P2.CODIGO_CLIENTE
AND DP.CODIGO_PRODUCTO = PR.CODIGO_PRODUCTO 
GROUP BY PR.NOMBRE,P.TOTAL,DP.PRECIO_UNIDADCANTIDAD
HAVING SUM(DP.CANTIDAD)+DP.PRECIO_UNIDADCANTIDAD > 3000;




-- CONSULTAS VARIADAS:


SELECT 
FROM CLIENTE c 
					  
							  