/*
ALTER SESSION SET "_oracle_script" = TRUE;
CREATE USER boletin7_1 IDENTIFIED BY boletin7_1;
GRANT CONNECT , RESOURCE , DBA TO boletin7_1;
*/

-- Ejercicio 1:

CREATE TABLE empleados (
    dni VARCHAR2(9) PRIMARY KEY,
    nomemp VARCHAR2(50),
    jefe VARCHAR2(9),
    departamento NUMBER,
    salario NUMBER(9,2) DEFAULT 1000,
    usuario VARCHAR2(50),
    fecha DATE,
    CONSTRAINT FK_JEFE FOREIGN KEY (jefe) REFERENCES empleados (dni) );


-- Ejercicio :

CREATE OR REPLACE
TRIGGER  T_EJ1
    BEFORE  INSERT ON BOLETIN7_1.EMPLEADOS
    FOR EACH ROW
    DECLARE
        CONT_JEFE NUMBER:=0;

    BEGIN
            SELECT count(*) INTO CONT_JEFE
            FROM empleados WHERE JEFE = :new.JEFE;

            IF   CONT_JEFE>4 THEN
                    RAISE_APPLICATION_ERROR('-20001',' Un jefe no puede tener mas 5 empleados');
            END IF;
    END;

/*
--INSERT INTO BOLETIN7_1.EMPLEADOS VALUES ('999999A', 'Joseba',  '999999A' , 1, 1000, 'Josebita', to_date('10/04/2001', 'DD/MM/YYYY'));
--INSERT INTO BOLETIN7_1.EMPLEADOS VALUES ('999999B', 'Paula',  '999999A' , 1, 1000, 'Josebita', to_date('10/04/2001', 'DD/MM/YYYY'));
--NSERT INTO BOLETIN7_1.EMPLEADOS VALUES ('999999S', 'Antonio',  '999999A' , 1, 1000, 'Josebita', to_date('10/04/2001', 'DD/MM/YYYY'));
--INSERT INTO BOLETIN7_1.EMPLEADOS VALUES ('999999F', 'Joaquin',  '999999A' , 1, 1000, 'Josebita', to_date('10/04/2001', 'DD/MM/YYYY'));
--INSERT INTO BOLETIN7_1.EMPLEADOS VALUES ('999999J', 'Euseba',  '999999A' , 1, 1000, 'Josebita', to_date('10/04/2001', 'DD/MM/YYYY'));
--INSERT INTO BOLETIN7_1.EMPLEADOS VALUES ('999999K', 'Euseba',  '999999A' , 1, 1000, 'Josebita', to_date('10/04/2001', 'DD/MM/YYYY'));
*/

-- Ejercicio 2:
CREATE OR REPLACE
TRIGGER  T_EJ2
    BEFORE  UPDATE ON BOLETIN7_1.EMPLEADOS
    FOR EACH ROW

    BEGIN
            IF  :NEW.SALARIO > (:OLD.SALARIO *1.2)  THEN
                RAISE_APPLICATION_ERROR('-20001',' El empleado no puede tener mas del 20 % de su salario');
            END IF;
    END;

SELECT * FROM BOLETIN7_1.EMPLEADOS;

UPDATE  BOLETIN7_1.EMPLEADOS SET SALARIO=2000 WHERE DNI='999999A';

-- Ejercicio 3:

CREATE TABLE empleados_baja(
    dni VARCHAR2(9) PRIMARY KEY,
    nomemp VARCHAR2 (50),
    jefe VARCHAR2(9),
    departamento NUMBER,
    salario NUMBER(9,2) DEFAULT 1000,
    usuario VARCHAR2(50),
    fecha DATE );


CREATE OR REPLACE
TRIGGER  T_EJ3_1
    AFTER DELETE ON EMPLEADOS
    FOR EACH ROW

    BEGIN
                INSERT INTO EMPLEADOS_BAJA VALUES  (:OLD.DNI, :OLD.NOMEMP, :OLD.JEFE, :OLD.DEPARTAMENTO, :OLD.SALARIO, USER , SYSDATE);
    END;

SELECT * FROM BOLETIN7_1.EMPLEADOS;

DELETE FROM BOLETIN7_1.EMPLEADOS WHERE EMPLEADOS.DNI='999999F';

SELECT * FROM BOLETIN7_1.EMPLEADOS_BAJA;


-- Ejercicio 4:

CREATE OR REPLACE
TRIGGER  T_EJ4
    BEFORE INSERT ON EMPLEADOS
    FOR EACH ROW
    DECLARE
        DEPART  NUMBER:=0;

    BEGIN
            SELECT E.DEPARTAMENTO
            INTO DEPART
            FROM EMPLEADOS E
            WHERE  DNI  LIKE  :NEW.JEFE ;

            IF  DEPART!=:NEW.DEPARTAMENTO THEN
                RAISE_APPLICATION_ERROR('-20001',' El Empleado y su jefe no pertenecen al mismo departamento ');
            END IF;

    END;

-- Ejercicio 5:
CREATE OR REPLACE
TRIGGER  T_EJ5
    BEFORE INSERT ON EMPLEADOS
    FOR EACH ROW
    DECLARE
                SUMA_SALARIO NUMBER;
    BEGIN
            SELECT  SUM(E.SALARIO)
            INTO SUMA_SALARIO
            FROM EMPLEADOS E
            WHERE E. DEPARTAMENTO  LIKE  :NEW.DEPARTAMENTO;

            IF  (SUMA_SALARIO+ :NEW.salario)>10000 THEN
                RAISE_APPLICATION_ERROR('-20001',' La suma de los salarios no supera a los 10000 ');
            END IF;

    END;


-- EJERCICIO 6:

CREATE TABLE controlCambios(
    usuario varchar2(30),
    fecha date,
    tipooperacion varchar2(30),
    datoanterior varchar2(30),
    datonuevo varchar2(30)
);

CREATE OR REPLACE TRIGGER T_EJ6
    AFTER UPDATE ON EMPLEADOS
    FOR EACH ROW

    BEGIN
            INSERT INTO CONTROLCAMBIOS VALUES (USER, SYSDATE, 'UPDATE', :OLD.DNI, :NEW.DNI);
    END;

UPDATE EMPLEADOS SET DNI= '999999Z' WHERE DNI='999999F';

SELECT * FROM BOLETIN7_1.EMPLEADOS;
SELECT * FROM CONTROLCAMBIOS ;



-- EJERCICIO 7:

CREATE OR REPLACE TRIGGER T_EJ7
    AFTER INSERT ON EMPLEADOS
    FOR EACH ROW

    BEGIN
            INSERT INTO CONTROLCAMBIOS VALUES (USER, SYSDATE, 'UPDATE',  NULL , :NEW.DNI);

    END;


INSERT INTO  EMPLEADOS VALUES ('12345W', 'Rafa', ' 999999A', 1 ,1000, 'Rafa02', to_date('22/06/2001', 'DD/MM/YYYY') );

SELECT * FROM CONTROLCAMBIOS;